### ISSUE TITLE
Grouped select does not cast values

### ISSUE THREAD

**Issue by marselmustafin** [PNixx/clickhouse-activerecord#39] opened 2021-02-10 11:19 UTC
Here's example grouped select, but the result values are strings instead of integers
![image](https://user-images.githubusercontent.com/19539397/107503284-d1004400-6baa-11eb-90e9-918e9de59e65.png)

**Comment by jbwl** [comment] 2023-06-29 07:07
This is still not fixed, and probably won't (seeing the issue is from early 2021).
Did you fix this in your project? Any hints how to mitigate this would be much appreciated.

**Comment by PNixx** [comment] 2023-10-13 13:21
Fixed in https://github.com/PNixx/clickhouse-activerecord/commit/191ac67ed5eba2e1cbd20306d855b85b603e54d4

**Closed by PNixx** 2023-10-13 13:21 UTC
